# Machine Learning

The objective of this phase is to train and compare machine learning models for predicting in-hospital mortality using information available within the first 24 hours of hospital admission.

The models will be compared against a simple majority-class baseline before more complex models are evaluated.

## Loading modelling data

In [57]:
import pandas as pd
import numpy as np

In [58]:
X_train = pd.read_csv("../data/processed/X_train_processed.csv")
X_test = pd.read_csv("../data/processed/X_test_processed.csv")

y_train = pd.read_csv("../data/processed/y_train.csv").squeeze()
y_test = pd.read_csv("../data/processed/y_test.csv").squeeze()

In [59]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (103, 21)
X_test: (26, 21)
y_train: (103,)
y_test: (26,)

## Majority-class baseline

In [60]:
baseline_prediction = y_train.mode()[0]

print("Baseline prediction:", baseline_prediction)

Baseline prediction: 0

In [61]:
baseline_predictions = np.full(
    shape=len(y_test),
    fill_value=baseline_prediction
)

In [62]:
from sklearn.metrics import accuracy_score

baseline_accuracy = accuracy_score(
    y_test,
    baseline_predictions
)

print("Baseline accuracy:", baseline_accuracy)

Baseline accuracy: 0.6923076923076923

In [63]:
from sklearn.metrics import confusion_matrix

baseline_cm = confusion_matrix(
    y_test,
    baseline_predictions
)

print(baseline_cm)

[[18  0]
 [ 8  0]]

### Baseline Recall

In [64]:
from sklearn.metrics import recall_score

baseline_recall = recall_score(
    y_test,
    baseline_predictions
)

print("Baseline mortality recall:", baseline_recall)

Baseline mortality recall: 0.0

## Logistic Regression

In [65]:
from sklearn.linear_model import LogisticRegression

In [66]:
logistic_model = LogisticRegression()

In [67]:
logistic_model.fit(X_train, y_train)

LogisticRegression()

In [68]:
logistic_predictions = logistic_model.predict(X_test)

In [69]:
logistic_predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0])

### Accuracy

In [70]:
from sklearn.metrics import accuracy_score

logistic_accuracy = accuracy_score(
    y_test,
    logistic_predictions
)

print("Logistic Regression accuracy:", logistic_accuracy)

Logistic Regression accuracy: 0.7307692307692307

### Mortality Recall

In [71]:
logistic_recall = recall_score(
    y_test,
    logistic_predictions
)

print("Logistic Regression mortality recall:", logistic_recall)

Logistic Regression mortality recall: 0.25

### Confusion Matrix

In [72]:
from sklearn.metrics import confusion_matrix

logistic_cm = confusion_matrix(
    y_test,
    logistic_predictions
)

print(logistic_cm)

[[17  1]
 [ 6  2]]

### Inspecting Coefficients

In [73]:
logistic_coefficients = pd.DataFrame({
    "feature": logistic_model.feature_names_in_,
    "coefficient": logistic_model.coef_[0]
})

logistic_coefficients

                                              feature  coefficient
0                               num__age_at_admission     0.419374
1                                    num__bicarbonate    -0.533305
2                                        num__calcium     0.089161
3                                     num__creatinine     0.573223
4                                        num__glucose     0.423218
5                                      num__magnesium    -0.039344
6                                      num__potassium     0.043534
7                                         num__sodium     0.107664
8                                  num__urea_nitrogen    -0.271063
9                                    num__haematocrit     0.414018
10                                   num__haemoglobin    -0.321383
11                                num__platelet_count    -0.071606
12                                           num__rdw     0.028127
13                             num__white_blood_cells     0.242583
14                                      cat__gender_M    -0.268372
15            cat__diagnosis_category_model_Digestive     0.394780
16           cat__diagnosis_category_model_Infectious    -0.250701
17  cat__diagnosis_category_model_Injury_poisoning...     0.130070
18            cat__diagnosis_category_model_Neoplasms    -0.204166
19                cat__diagnosis_category_model_Other    -0.348649
20          cat__diagnosis_category_model_Respiratory     0.341605

In [74]:
logistic_coefficients.sort_values(
    "coefficient",
    ascending=False
)

                                              feature  coefficient
3                                     num__creatinine     0.573223
4                                        num__glucose     0.423218
0                               num__age_at_admission     0.419374
9                                    num__haematocrit     0.414018
15            cat__diagnosis_category_model_Digestive     0.394780
20          cat__diagnosis_category_model_Respiratory     0.341605
13                             num__white_blood_cells     0.242583
17  cat__diagnosis_category_model_Injury_poisoning...     0.130070
7                                         num__sodium     0.107664
2                                        num__calcium     0.089161
6                                      num__potassium     0.043534
12                                           num__rdw     0.028127
5                                      num__magnesium    -0.039344
11                                num__platelet_count    -0.071606
18            cat__diagnosis_category_model_Neoplasms    -0.204166
16           cat__diagnosis_category_model_Infectious    -0.250701
14                                      cat__gender_M    -0.268372
8                                  num__urea_nitrogen    -0.271063
10                                   num__haemoglobin    -0.321383
19                cat__diagnosis_category_model_Other    -0.348649
1                                    num__bicarbonate    -0.533305

#### Generating OR table

In [75]:
logistic_coefficients["odds_ratio"] = np.exp(logistic_coefficients["coefficient"])

In [76]:
logistic_coefficients.sort_values("odds_ratio", ascending=False)

                                              feature  coefficient  odds_ratio
3                                     num__creatinine     0.573223    1.773976
4                                        num__glucose     0.423218    1.526867
0                               num__age_at_admission     0.419374    1.521009
9                                    num__haematocrit     0.414018    1.512885
15            cat__diagnosis_category_model_Digestive     0.394780    1.484058
20          cat__diagnosis_category_model_Respiratory     0.341605    1.407204
13                             num__white_blood_cells     0.242583    1.274537
17  cat__diagnosis_category_model_Injury_poisoning...     0.130070    1.138909
7                                         num__sodium     0.107664    1.113673
2                                        num__calcium     0.089161    1.093256
6                                      num__potassium     0.043534    1.044496
12                                           num__rdw     0.028127    1.028526
5                                      num__magnesium    -0.039344    0.961420
11                                num__platelet_count    -0.071606    0.930898
18            cat__diagnosis_category_model_Neoplasms    -0.204166    0.815327
16           cat__diagnosis_category_model_Infectious    -0.250701    0.778255
14                                      cat__gender_M    -0.268372    0.764623
8                                  num__urea_nitrogen    -0.271063    0.762568
10                                   num__haemoglobin    -0.321383    0.725145
19                cat__diagnosis_category_model_Other    -0.348649    0.705641
1                                    num__bicarbonate    -0.533305    0.586663

## Random Forest

In [77]:
from sklearn.ensemble import RandomForestClassifier

In [78]:
random_forest = RandomForestClassifier(
    random_state=42
)

In [79]:
random_forest.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [80]:
random_forest_predictions = random_forest.predict(X_test)

In [81]:
from sklearn.metrics import accuracy_score, recall_score, confusion_matrix

rf_accuracy = accuracy_score(
    y_test,
    random_forest_predictions
)

rf_recall = recall_score(
    y_test,
    random_forest_predictions
)

rf_cm = confusion_matrix(
    y_test,
    random_forest_predictions
)

print("Random Forest accuracy:", rf_accuracy)
print("Random Forest mortality recall:", rf_recall)
print("Random Forest confusion matrix:\n", rf_cm)

Random Forest accuracy: 0.6538461538461539
Random Forest mortality recall: 0.125
Random Forest confusion matrix:
 [[16  2]
 [ 7  1]]

### Inspecting importance

In [82]:
rf_importances = pd.DataFrame({
    "feature": X_train.columns,
    "importance": random_forest.feature_importances_
})

In [83]:
rf_importances.sort_values(
    "importance",
    ascending=False
)

                                              feature  importance
0                               num__age_at_admission    0.111843
4                                        num__glucose    0.104012
1                                    num__bicarbonate    0.075107
11                                num__platelet_count    0.073199
13                             num__white_blood_cells    0.068727
2                                        num__calcium    0.068486
7                                         num__sodium    0.066406
8                                  num__urea_nitrogen    0.064383
9                                    num__haematocrit    0.061460
10                                   num__haemoglobin    0.060855
5                                      num__magnesium    0.050259
3                                     num__creatinine    0.049957
12                                           num__rdw    0.049297
6                                      num__potassium    0.048501
14                                      cat__gender_M    0.012370
15            cat__diagnosis_category_model_Digestive    0.008194
16           cat__diagnosis_category_model_Infectious    0.007411
17  cat__diagnosis_category_model_Injury_poisoning...    0.006895
18            cat__diagnosis_category_model_Neoplasms    0.005020
20          cat__diagnosis_category_model_Respiratory    0.004984
19                cat__diagnosis_category_model_Other    0.002635

## XGBoost

In [84]:
import xgboost

In [85]:
from xgboost import XGBClassifier

In [86]:
xgb_model = XGBClassifier(
    random_state=42
)

In [87]:
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [88]:
xgb_predictions = xgb_model.predict(X_test)

In [89]:
xgb_accuracy = accuracy_score(
    y_test,
    xgb_predictions
)

xgb_recall = recall_score(
    y_test,
    xgb_predictions
)

xgb_cm = confusion_matrix(
    y_test,
    xgb_predictions
)

print("XGBoost accuracy:", xgb_accuracy)
print("XGBoost mortality recall:", xgb_recall)
print("XGBoost confusion matrix:\n", xgb_cm)

XGBoost accuracy: 0.6538461538461539
XGBoost mortality recall: 0.25
XGBoost confusion matrix:
 [[15  3]
 [ 6  2]]

## Cross-validation

In [90]:
from sklearn.model_selection import StratifiedKFold, cross_validate
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression

In [91]:
final_data = pd.read_csv("../data/processed/final_data.csv")

In [92]:
lab_columns = [
    "bicarbonate",
    "calcium",
    "creatinine",
    "glucose",
    "magnesium",
    "potassium",
    "sodium",
    "urea_nitrogen",
    "haematocrit",
    "haemoglobin",
    "platelet_count",
    "rdw",
    "white_blood_cells"
]

categorical_features = [
    "gender",
    "diagnosis_category_model"
]

numerical_features = [
    "age_at_admission"
] + lab_columns

In [93]:
feature_columns = numerical_features + categorical_features

X_raw = final_data[feature_columns].copy()
y_raw = final_data["hospital_expire_flag"]

In [94]:
from sklearn.model_selection import train_test_split

X_train_raw, X_test_raw, y_train_raw, y_test_raw = train_test_split(
    X_raw,
    y_raw,
    test_size=0.20,
    random_state=42,
    stratify=y_raw
)

In [95]:
print(X_train_raw.shape) 
print(X_test_raw.shape)

(103, 16)
(26, 16)

In [96]:
numerical_pipeline_cv = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

In [97]:
preprocessor_cv = ColumnTransformer([
    ("num", numerical_pipeline_cv, numerical_features),
    ("cat", OneHotEncoder(
        drop="first",
        handle_unknown="ignore"
    ), categorical_features)
])

In [98]:
logistic_pipeline = Pipeline([
    ("preprocessor", preprocessor_cv),
    ("model", LogisticRegression())
])

### Cross-validating Logistic Regression

In [99]:
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [100]:
cv_results_logistic = cross_validate(
    logistic_pipeline,
    X_train_raw,
    y_train_raw,
    cv=cv,
    scoring=["accuracy", "recall"]
)

In [101]:
print("Accuracy by fold:", cv_results_logistic["test_accuracy"])
print("Recall by fold:", cv_results_logistic["test_recall"])

print("Mean accuracy:", cv_results_logistic["test_accuracy"].mean())
print("Mean recall:", cv_results_logistic["test_recall"].mean())

Accuracy by fold: [0.61904762 0.71428571 0.61904762 0.55       0.55      ]
Recall by fold: [0.16666667 0.42857143 0.28571429 0.         0.16666667]
Mean accuracy: 0.6104761904761904
Mean recall: 0.20952380952380953

### Cross-validating Random Forest

In [102]:
random_forest_pipeline = Pipeline([
    ("preprocessor", preprocessor_cv),
    ("model", RandomForestClassifier(random_state=42))
])

In [103]:
cv_results_rf = cross_validate(
    random_forest_pipeline,
    X_train_raw,
    y_train_raw,
    cv=cv,
    scoring=["accuracy", "recall"]
)

In [104]:
print("Accuracy by fold:", cv_results_rf["test_accuracy"])
print("Recall by fold:", cv_results_rf["test_recall"])

print("Mean accuracy:", cv_results_rf["test_accuracy"].mean())
print("Mean recall:", cv_results_rf["test_recall"].mean())

Accuracy by fold: [0.66666667 0.57142857 0.61904762 0.6        0.65      ]
Recall by fold: [0.16666667 0.         0.         0.         0.        ]
Mean accuracy: 0.6214285714285714
Mean recall: 0.03333333333333333

### Cross-validating XGBoost

In [105]:
xgb_pipeline = Pipeline([
    ("preprocessor", preprocessor_cv),
    ("model", XGBClassifier(random_state=42))
])

In [106]:
cv_results_xgb = cross_validate(
    xgb_pipeline,
    X_train_raw,
    y_train_raw,
    cv=cv,
    scoring=["accuracy", "recall"]
)

In [107]:
print("Accuracy by fold:", cv_results_xgb["test_accuracy"])
print("Recall by fold:", cv_results_xgb["test_recall"])

print("Mean accuracy:", cv_results_xgb["test_accuracy"].mean())
print("Mean recall:", cv_results_xgb["test_recall"].mean())

Accuracy by fold: [0.57142857 0.52380952 0.47619048 0.55       0.6       ]
Recall by fold: [0.16666667 0.         0.         0.16666667 0.16666667]
Mean accuracy: 0.5442857142857144
Mean recall: 0.1

### Summary

In [108]:
print("Logistic accuracy SD:", cv_results_logistic["test_accuracy"].std())
print("Logistic recall SD:", cv_results_logistic["test_recall"].std())

print("Random Forest accuracy SD:", cv_results_rf["test_accuracy"].std())
print("Random Forest recall SD:", cv_results_rf["test_recall"].std())

print("XGBoost accuracy SD:", cv_results_xgb["test_accuracy"].std())
print("XGBoost recall SD:", cv_results_xgb["test_recall"].std())

Logistic accuracy SD: 0.06039552175136039
Logistic recall SD: 0.14238015607358145
Random Forest accuracy SD: 0.034139901578923666
Random Forest recall SD: 0.06666666666666667
XGBoost accuracy SD: 0.04226039568063579
XGBoost recall SD: 0.0816496580927726

In [109]:
model_summary = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "XGBoost"
    ],
    "Mean CV Accuracy": [
        cv_results_logistic["test_accuracy"].mean(),
        cv_results_rf["test_accuracy"].mean(),
        cv_results_xgb["test_accuracy"].mean()
    ],
    "Accuracy SD": [
        cv_results_logistic["test_accuracy"].std(),
        cv_results_rf["test_accuracy"].std(),
        cv_results_xgb["test_accuracy"].std()
    ],
    "Mean CV Recall": [
        cv_results_logistic["test_recall"].mean(),
        cv_results_rf["test_recall"].mean(),
        cv_results_xgb["test_recall"].mean()
    ],
    "Recall SD": [
        cv_results_logistic["test_recall"].std(),
        cv_results_rf["test_recall"].std(),
        cv_results_xgb["test_recall"].std()
    ]
})

model_summary

,Model,Mean CV Accuracy,Accuracy SD,Mean CV Recall,Recall SD
0,Logistic Regression,0.610476,0.060396,0.209524,0.142380
1,Random Forest,0.621429,0.034140,0.033333,0.066667
2,XGBoost,0.544286,0.042260,0.100000,0.081650

## Threshold Analysis

In [110]:
from sklearn.model_selection import cross_val_predict

In [111]:
logistic_oof_proba = cross_val_predict(
    logistic_pipeline,
    X_train_raw,
    y_train_raw,
    cv=cv,
    method="predict_proba"
)[:, 1]

In [112]:
from sklearn.metrics import recall_score, precision_score

thresholds = [0.5, 0.4, 0.3, 0.2]

for threshold in thresholds:
    predictions = (logistic_oof_proba >= threshold).astype(int)
    
    print(
        f"Threshold {threshold}: "
        f"Recall = {recall_score(y_train_raw, predictions):.2f}, "
        f"Precision = {precision_score(y_train_raw, predictions):.2f}"
    )

Threshold 0.5: Recall = 0.22, Precision = 0.32
Threshold 0.4: Recall = 0.28, Precision = 0.29
Threshold 0.3: Recall = 0.44, Precision = 0.32
Threshold 0.2: Recall = 0.56, Precision = 0.29

## Machine Learning Conclusions

Three classification models were investigated: Logistic Regression, Random Forest and XGBoost. Logistic Regression produced the strongest overall mortality recall during cross-validation, while Random Forest achieved marginally higher mean accuracy but very poor mortality recall. XGBoost performed worse than the majority-class baseline in mean cross-validated accuracy.

Cross-validation also demonstrated substantial variability in model performance across folds, particularly for mortality recall, reflecting the small number of admissions and deaths available in the MIMIC-III demo dataset.

Threshold analysis demonstrated that reducing the Logistic Regression classification threshold from 0.50 to 0.30 increased out-of-fold mortality recall from 22% to 44%, while maintaining an observed precision of approximately 32%. This illustrates the trade-off between sensitivity and false-positive predictions when selecting a classification threshold.

Logistic Regression was therefore selected as the primary model for subsequent evaluation. However, the results should be interpreted as a proof-of-concept rather than evidence of clinical validity, given the very small sample size and limited number of mortality events.